# Generated by Django 4.2.9 on 2024-02-03 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmcode',
            options={'verbose_name': 'Код подтврждения', 'verbose_name_plural': 'Коды подтверждения'},
        ),
        migrations.AlterModelTable(
            name='confirmcode',
            table='confirm_code',
        ),
    ]
