# Generated by Django 4.2.9 on 2024-01-26 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_movie_category_movie_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(default='Doesn`t exist', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='movies', to='movie_app.director'),
        ),
    ]
