# Generated by Django 4.2.9 on 2024-02-03 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_alter_movie_director'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'Директор', 'verbose_name_plural': 'Директоры'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Кино', 'verbose_name_plural': 'Кино'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelTable(
            name='director',
            table='directors',
        ),
        migrations.AlterModelTable(
            name='movie',
            table='movies',
        ),
        migrations.AlterModelTable(
            name='review',
            table='reviews',
        ),
    ]
